name: Demo Review Deployments

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fake build
        run: |
          echo "Build xong!"

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging           # trùng tên environment đã tạo
    steps:
      - name: Deploy to staging
        run: |
          echo "Đang deploy lên STAGING..."
          # Demo giả lập deploy
          sleep 5
          echo "Deploy xong STAGING!"
